spring.application.name=pulsedesk
spring.profiles.active=local


# H2 db
spring.datasource.url=jdbc:h2:mem:pulsedeskdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


huggingface.api.url=https://router.huggingface.co/hf-inference/models/facebook/bart-large-mnli
huggingface.api.token=${api.token}